!SESSION 2019-12-14 17:09:20.596 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.ti.ccstudio.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.ti.ccstudio.branding.product

This is a continuation of log file C:\Users\Alan\Downloads\tirslk_max_1_00_00\.metadata\.bak_0.log
Created Time: 2019-12-15 16:30:47.895

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:30:47.911
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:32:12.093
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:33:26.052
!MESSAGE DS_ERROR: CORTEX_M4_0: JTAG Communication Error: (Error -613 @ 0x0) The target indicates that it is busy.  Either try the SWD request  again, or abort the transaction. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:33:26.130
!MESSAGE DS_ERROR: CORTEX_M4_0: Failed to remove the debug state from the target before disconnecting.  There may still be breakpoint op-codes embedded in program memory.  It is recommended that you reset the emulator before you connect and reload your program before you continue debugging


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:34:40.667
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:34:40.950
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -614 @ 0x0) The target indicates there is an error condition from a previous SWD  request. Clear the error the condition, and try the SWD request again. (Emulation package 8.3.0.00003) 


!ENTRY com.ti.ccstudio.debug 1 0 2019-12-15 16:34:41.143
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -614 @ 0x0)
The target indicates there is an error condition from a previous SWD 
request. Clear the error the condition, and try the SWD request again.
(Emulation package 8.3.0.00003)


!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:39:41.435
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:40:24.810
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 4 0 2019-12-15 16:41:26.865
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:295)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:356)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:418)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:408)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1057)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:139)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more
